@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.vidarin.wheatrevolution.compat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;