@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.vidarin.wheatrevolution.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;