@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.vidarin.wheatrevolution.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;